# permissions for end users to view fabricorderers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fabricorderer-viewer-role
rules:
- apiGroups:
  - fabric.kompitech.com
  resources:
  - fabricorderers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fabric.kompitech.com
  resources:
  - fabricorderers/status
  verbs:
  - get
