apiVersion: hl-fabric.kompitech.com/v1alpha1
kind: FabricPeer
metadata:
  name: peer1
  namespace: 2657db63-8a32-41c6-814c-6fa3d21c4731
  annotations:
    region: Region1
    fqdn: peer1.alice.example.com
spec:
  svcType: ClusterIP
  bootstrapnodeaddress:
  certvolumesize:  1Gi
  commonname:      peer1.alice.example.com
  datavolumesize:  1Gi
  image:           hyperledger/fabric-peer:1.4
  organization:    2657db63-8a32-41c6-814c-6fa3d21c4731
  certificate:
    admincerts:
    - Name: admin1
      Value: |-
        -----BEGIN CERTIFICATE-----
        MIIB2TCCAX+gAwIBAgIUcBALp7q6+j3GVMkuH11W8Vb0N/gwCgYIKoZIzj0EAwIw
        HDEaMBgGA1UEAxMRYWxpY2UuZXhhbXBsZS5jb20wHhcNMTgxMjIxMTQ0NDI2WhcN
        MjMxMjIwMTQ0NDU2WjAjMSEwHwYDVQQDExhhZG1pbjIuYWxpY2UuZXhhbXBsZS5j
        b20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARgcH5Df4Mq9sCFktBXj69+3Spd
        Ah7ixi4uA4Zu3DfoTOj1USThIVqyLYepdpT0zBBDDMLuydVQJAkWonj8G8q9o4GX
        MIGUMA4GA1UdDwEB/wQEAwIDqDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
        AwIwHQYDVR0OBBYEFLc34kU4e6sLCUPeV0j5O7pVL7UJMB8GA1UdIwQYMBaAFEjz
        bEYE8uey56/4KDBKrL5U5p4wMCMGA1UdEQQcMBqCGGFkbWluMi5hbGljZS5leGFt
        cGxlLmNvbTAKBggqhkjOPQQDAgNIADBFAiBmHubGuugjSCNprB0yGeTdi6q+6mCd
        DBBCNTwN1XU+BgIhAOgYESDLs3sQabPkPTGAlVMA4vJKIZrMqxdbJb9Pi+2Z
        -----END CERTIFICATE-----
    - Name: admin2
      Value: |-
        -----BEGIN CERTIFICATE-----
        MIIB1zCCAX2gAwIBAgIUOLrxlZOurKGQXAO4kwN8dKXNkvMwCgYIKoZIzj0EAwIw
        HDEaMBgGA1UEAxMRYWxpY2UuZXhhbXBsZS5jb20wHhcNMTgxMjIxMTQ0NDI1WhcN
        MTkxMjIxMjA0NDU1WjAiMSAwHgYDVQQDExdhZG1pbi5hbGljZS5leGFtcGxlLmNv
        bTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABPZwdwp/lMO0oito/c6/OdQ4aXjG
        Fhx2hGZZNBhWqjbFSZEihxDEGcZYboceloTqblAMLTZKmAaV/+goRUGbXCWjgZYw
        gZMwDgYDVR0PAQH/BAQDAgOoMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
        AjAdBgNVHQ4EFgQUtT1UavTk9As5e2aLU2cku8vejjYwHwYDVR0jBBgwFoAUSPNs
        RgTy57Lnr/goMEqsvlTmnjAwIgYDVR0RBBswGYIXYWRtaW4uYWxpY2UuZXhhbXBs
        ZS5jb20wCgYIKoZIzj0EAwIDSAAwRQIgOTGPny59qZAwAF6rdbEeUGip0xkd1Tva
        d812u1GSOooCIQCaXjXu6aT11BTmJPY96ssX4RJ4R1RYvTVufNx7U1QIfA==
        -----END CERTIFICATE-----
    cacerts:
    - Name: root
      Value: |-
        -----BEGIN CERTIFICATE-----
        MIIBuzCCAWKgAwIBAgIUMVoZvRWKiTAGqgYIyXtKAPM0XSgwCgYIKoZIzj0EAwIw
        HDEaMBgGA1UEAxMRYWxpY2UuZXhhbXBsZS5jb20wHhcNMTgxMjIxMTQ0NDIyWhcN
        MjgxMjE0MTA0NDUyWjAcMRowGAYDVQQDExFhbGljZS5leGFtcGxlLmNvbTBZMBMG
        ByqGSM49AgEGCCqGSM49AwEHA0IABCReKYylfGh1v2/cAzaj3FlgZqtuHa2feHka
        tNjypmsM3CytfkRFUPsQnYIQBO5KwqAQiClWe+8z1ACuQ0kgoU+jgYEwfzAOBgNV
        HQ8BAf8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUSPNsRgTy57Ln
        r/goMEqsvlTmnjAwHwYDVR0jBBgwFoAUSPNsRgTy57Lnr/goMEqsvlTmnjAwHAYD
        VR0RBBUwE4IRYWxpY2UuZXhhbXBsZS5jb20wCgYIKoZIzj0EAwIDRwAwRAIgC5K9
        UtAb4CqXnQGSqBrloDWN4KknHxau7Uj7b7g5O9ECIGqC0uaQNExEZMZ3NQ2WgTRu
        kP1lJD2Yy/pcc1P3PR4C
        -----END CERTIFICATE-----
  containers:
  - name: "peer"
    resources:
      limits: 200m
      requests: 500Mi
    image: "image"
  - name: "dind"
    resources:
      limits: 1
      requests: 1500Mi
    image: "image"
  - name: "couchdb"
    resources:
      limits: 200m
      requests: 500Mi
    image: "image"